### ISSUE TITLE
Bisa bantu gan?

### ISSUE THREAD

**Issue by ridhoilhamr** [adhiariyadi/Sistem-Informasi-Akademik-Sekolah-Laravel#19]
Your lock file does not contain a compatible set of packages. Please run composer update.

Problem 1
- dompdf/dompdf is locked to version v0.8.6 and an update of this package was not requested.
- dompdf/dompdf v0.8.6 requires php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
Problem 2
- paragonie/random_compat is locked to version v9.99.99 and an update of this package was not requested.
- paragonie/random_compat v9.99.99 requires php ^7 -> your php version (8.0.2) does not satisfy that requirement.
Problem 3
- phpoffice/phpspreadsheet is locked to version 1.16.0 and an update of this package was not requested.
- phpoffice/phpspreadsheet 1.16.0 requires ext-gd * -> it is missing from your system. Install or enable PHP's gd extension.
Problem 4
- fzaninotto/faker is locked to version v1.9.2 and an update of this package was not requested.
- fzaninotto/faker v1.9.2 requires php ^5.3.3 || ^7.0 -> your php version (8.0.2) does not satisfy that requirement.
Problem 5
- dompdf/dompdf v0.8.6 requires php ^7.1 -> your php version (8.0.2) does not satisfy that requirement.
- barryvdh/laravel-dompdf v0.8.7 requires dompdf/dompdf ^0.8 -> satisfiable by dompdf/dompdf[v0.8.6].
- barryvdh/laravel-dompdf is locked to version v0.8.7 and an update of this package was not requested.

**Comment by adhiariyadi** [comment]
wah belom pernah nyoba install pakek php versi 8

**Comment by adhiariyadi** [comment]
> Saranya gimana ya enaknya bang?

coba install pakek php versi 7.3/7.4

**Comment by ridhoilhamr** [comment]
> > ini kenapa ya gan?
> > PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists")
> > C:\xampp\htdocs\Sistem-Informasi-Akademik-Sekolah-Laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:46
> 
> udah migrate belom?

php artisan migrate --seed. Pakai yang ini kan?

**Comment by adhiariyadi** [comment]
> > > ini kenapa ya gan?
> > > PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists")
> > > C:\xampp\htdocs\Sistem-Informasi-Akademik-Sekolah-Laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:46
> > 
> > 
> > udah migrate belom?
> 
> php artisan migrate --seed. Pakai yang ini kan?

iya ikutin cara install nya aja udah saya tulis di readme

**Comment by ridhoilhamr** [comment]
> > > > > ini kenapa ya gan?
> > > > > PDOException::("SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'users' already exists")
> > > > > C:\xampp\htdocs\Sistem-Informasi-Akademik-Sekolah-Laravel\vendor\laravel\framework\src\Illuminate\Database\Connection.php:46
> > > > 
> > > > 
> > > > udah migrate belom?
> > > 
> > > 
> > > php artisan migrate --seed. Pakai yang ini kan?
> > 
> > 
> > iya ikutin cara install nya aja udah saya tulis di readme
> 
> udah bang

masih aja bang

**Comment by adhiariyadi** [comment]
coba ulang aja, harusnya sih udah bisa
