### ISSUE TITLE
Error pada menu siswa, ulangan dan rapor

### ISSUE THREAD

**Issue by thegenzo** [adhiariyadi/Sistem-Informasi-Akademik-Sekolah-Laravel#23]
Halo gan, terimakasih sudah mau berbagi source code project nya yang keren ini. Disini saya menemukan beberapa error pada sistemnya. Ini adalah pertama kali saya mempost issues saat menggunakan github jadi mohon maaf jika ada kata yang tidak berkenan

**Error saat proses store data pada siswa**
Error Code:  Class 'App\Http\Controllers\Guru' not found 
Di SiswaController menggunakan model Guru saat melakukan store data. Mungkin akan berhasil jika menggunakan model Siswa.
![image](https://user-images.githubusercontent.com/23573634/138446423-ec698b43-7186-4d18-bf1c-9f7cffad9fc0.png)

**Error saat mengakses menu rapot saat login sebagai siswa**
Error Code: Trying to access array offset on value of type null (View: C:\Users\losca\OneDrive\Dokumen\myCode\belajar\github\adhiariyadi-Sistem-Informasi-Akademik-Sekolah-Laravel-master\resources\views\siswa\rapot.blade.php) 
![image](https://user-images.githubusercontent.com/23573634/138447420-5258f5b4-6f53-412c-82fb-cb0f78c02bda.png)

**Error saat mengakses menu ulangan saat login sebagai siswa**
Error Code: Trying to access array offset on value of type null (View: C:\Users\losca\OneDrive\Dokumen\myCode\belajar\github\adhiariyadi-Sistem-Informasi-Akademik-Sekolah-Laravel-master\resources\views\siswa\ulangan.blade.php) 
![image](https://user-images.githubusercontent.com/23573634/138447630-d1b7b6f9-8cc6-4fe2-86d9-9ef1fa42f019.png)

Semoga open issue dari saya bisa membuat project agan bisa lebih baik lagi 
Terimakasih

**Comment by adhiariyadi** [comment]
terimakasih atas laporannya segera saya proses untuk bug nya
